[package]
name = "game-of-life"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
crossterm = "0.28.1"
rand = "0.9.0"
ratatui = "0.29.0"
tracing = "0.1.41"
tracing-subscriber = "0.3"
