[package]
name = "gol"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ 
  "configuration",
  "game", 
  "runner", 
  "view", 
  "websocket"
]

[[bin]]
name = "main"
path = "./runner/src/main.rs"
